services:
  db:
    image: postgis/postgis:16-3.4
    container_name: med_db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: med
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: med_redis
    ports:
      - '6379:6379'

volumes:
  db_data:
